In [1]:
import yt

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from opmd_viewer import OpenPMDTimeSeries
import h5py
%matplotlib notebook
# or `%matplotlib inline` for non-interactive plots

In [2]:
ts = OpenPMDTimeSeries('/Volumes/Lacie-5TB/test')


KeyError: "Can't open attribute (Can't locate attribute: 'timeunitsi')"

In [4]:
ts.slider()

NameError: name 'ts' is not defined

In [7]:
f = yt.load('../EMF/*.h5')

In [8]:
for handles in f:
    print handles

yt : [INFO     ] 2018-07-24 17:24:33,783 open_pmd - found 8 iterations in directory


UnboundLocalError: local variable 'shape' referenced before assignment

In [9]:
f[1].derived_field_list


yt : [INFO     ] 2018-07-24 17:24:48,309 open_pmd - found 8 iterations in directory


UnboundLocalError: local variable 'shape' referenced before assignment

In [1]:
import h5py

In [3]:
data=h5py.File('/Users/franktsung/Documents/work/codes/upic-emma-2.0/EMF/EandB00000055.h5')

In [4]:
list(data.attrs.items())

[(u'openPMD', '1.0.0'),
 (u'openPMDextension', 0),
 (u'basePath', '/data/%T/'),
 (u'meshesPath', 'fields/'),
 (u'particlesPath', 'particles/'),
 (u'iterationEncoding', 'fileBased'),
 (u'iterationFormat', 'EandB%T.h5')]

In [5]:
list(data['data']['00000055']['fields']['B1'].attrs.items())

[(u'axisLabels', array(['x', 'y'], 
        dtype='|S10')),
 (u'dataOrder', 'F'),
 (u'geometry', 'cartesian'),
 (u'geometryParameters', 'cartesian'),
 (u'gridGlobalOffset', array([ 0.,  0.])),
 (u'gridSpacing', array([ 1.,  1.], dtype=float32)),
 (u'gridUnitSI', 1.0),
 (u'timeOffset', 0.0),
 (u'unitDimension', array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])),
 (u'position', array([ 0.,  0.], dtype=float32)),
 (u'unitSI', 1.0)]

In [3]:
data3=h5py.File('/Volumes/Lacie-5TB/test/test.h5')

In [4]:
list(data3.attrs.items())

[(u'DT', array([ 1.])),
 (u'ITER', array([0])),
 (u'MOVE C', array([0])),
 (u'PERIODIC', array([0])),
 (u'TIME', array([ 0.])),
 (u'TIME UNITS', array([''], 
        dtype='|S1')),
 (u'TYPE', array(['grid'], 
        dtype='|S4')),
 (u'XMIN', array([ 0.])),
 (u'XMAX', array([ 0.])),
 (u'openPMD', '1.0.0'),
 (u'openPMDextension', 0),
 (u'iterationEncoding', 'fileBased'),
 (u'basePath', array(['/data/%T'], 
        dtype='|S8')),
 (u'meshesPath', array(['mesh/'], 
        dtype='|S5')),
 (u'particlesPath', array(['particles/'], 
        dtype='|S10'))]

In [102]:
list(data3['data']['20']['mesh']['e3'].attrs.items())

[(u'dataOrder', array(['F'], 
        dtype='|S1')), (u'geometry', array(['cartesian'], 
        dtype='|S9')), (u'geometryParameters', array(['cartesian'], 
        dtype='|S9')), (u'axisLabels', array(['x1', 'x2'], 
        dtype='|S2')), (u'gridUnitSI', 1.0), (u'position',
  array([ 0.,  0.], dtype=float32)), (u'gridSpacing',
  array([ 0.31431639,  1.25      ], dtype=float32)), (u'gridGlobalOffset',
  array([ 0.,  0.]))]

In [2]:
data2=h5py.File('/Volumes/Lacie-5TB/runs/compass-2018/MS/FLD/e3/e3-000002.h5')

NameError: name 'h5py' is not defined

In [75]:
list(data2['e3'].attrs.items())

[(u'UNITS', array(['m_e c \\omega_p e^{-1}'], 
        dtype='|S64')), (u'LONG_NAME', array(['E_3'], 
        dtype='|S64')), (u'axisLabels', array(['x1', 'x2'], 
        dtype='|S2')), (u'dataOrder', array(['F'], 
        dtype='|S1')), (u'geometry', array(['cartesian'], 
        dtype='|S9')), (u'geometryParameters', array(['cartesian'], 
        dtype='|S9')), (u'gridGlobalOffset',
  array([ 0.,  0.])), (u'gridUnitSI', array([ 1.])), (u'position',
  array([ 0.,  0.], dtype=float32)), (u'gridSpacing',
  array([ 1.,  1.], dtype=float32))]

In [53]:
list(data2.attrs.items())

[(u'NAME', array(['e3'], 
        dtype='|S256')), (u'TYPE', array(['grid'], 
        dtype='|S4')), (u'openPMD', array(['1.0.0'], 
        dtype='|S5')), (u'openPMDextension',
  array([0], dtype=int32)), (u'basePath', array(['.'], 
        dtype='|S1')), (u'meshesPath', array(['MS/FLD//e3/'], 
        dtype='|S256')), (u'iterationEncoding', array(['fileBased'], 
        dtype='|S9')), (u'iterationFormat',
  array([ 'e3                                                                                                                                                                                                                                                              %T.h5'], 
        dtype='|S261')), (u'TIME', array([ 5.])), (u'ITER',
  array([20], dtype=int32)), (u'DT', array([ 1.])), (u'TIME UNITS',
  array(['1 / \\omega_p'], 
        dtype='|S256')), (u'NX', array([512, 512], dtype=int32)), (u'XMIN',
  array([ 5.0290625,  0.       ])), (u'XMAX',
  array([ 165.9590625,  640.       

In [64]:
import numpy as np
dx=(data2.attrs['XMAX']-data2.attrs['XMIN']/np.shape(data2['e3']))

In [65]:
print(dx)

[ 165.94924011  640.        ]
